# Second Order Feedback Linearization 6-DOF PID Controller for the VTec U-IV gains

# Format: [x, y, z, phi, theta_, psi]
# k_p: [4.5, 5, 4.5, 60, 40, 80]
# k_i: [0, 0, 0, 0, 0.01, 0.01]
# k_d: [3, 5, 4, 7, 5, 20]

k_p: [1, 1, 1, 1, 1, 1]
k_i: [0, 0, 0, 0, 0, 0]
k_d: [1, 1, 1, 1, 1, 1]